// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alhctsqjhnbglqkvrspg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsaGN0c3FqaG5iZ2xxa3Zyc3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODY5NDUsImV4cCI6MjA1OTk2Mjk0NX0.aERWNL-3-zdLm36geAc7iwyHMdOBKhHpPoHxpCMZCYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);